import Head from 'next/head'
import Header from '../components/header'
import Layout from '../components/layout'
import Banner from '../components/banner'
import SectionProducts from '../components/section-products'
import { useState, useEffect } from 'react'
import db from '../db/index'
import SectionProductsContainer from '../components/section-products-container'
import Modal from '../components/modal-portal'
import AddedCartAlert from '../components/added-cart-alert'
import { useCartContext } from '../contexts/cart-context'

export default function Home() {
  let [popular, setAllPopular] = useState(null)
  let [offertProducts, setOffertProducts] = useState(null)
  let [ modal, setModal ] = useState(false)
  let [ address, setAddress ] = useState('México City Marriott Reforma Hotel Puta')
  let [ oneSelectProduct, setOneProduct ] = useState()
  let [ isAdded, setIsAdded ] = useState(false)
  let { cart, setCart } = useCartContext() 

  useEffect(() => {
    if(db){
      let productsOffert = db.filter( product  => product.price.offert)
      setOffertProducts(productsOffert)
      let mostPopularProduct = db.filter( product => product.popular)
      setAllPopular(mostPopularProduct)
    }

    if(cart.length !== 0){
      setIsAdded(true)
      setTimeout(() => {
        setIsAdded(false)
      }, 2000)

      if(typeof window !== 'undefined'){
        localStorage.setItem('cart', JSON.stringify(cart))
      }

    } else {
      console.log(cart)
      if(typeof window !== 'undefined'){
        localStorage.removeItem('cart')
      }
    }


  }, [cart])



  return (
    <Layout>
      <Head>
        <title>Tiendita project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Modal 
        product={oneSelectProduct} 
        setAddress={setAddress} 
        modal={modal} 
        setModal={setModal}
        address={address}
        />

      {cart.length !== 0 ? <AddedCartAlert added={isAdded} /> : null}
      
      <Header address={address} setModal={setModal} />
      <Banner  />
      <SectionProductsContainer>
        <SectionProducts setOneProduct={setOneProduct} setModal={setModal} title="Ofertas" products={offertProducts} />
        <SectionProducts setOneProduct={setOneProduct} setModal={setModal} title="Lo más popular" products={popular} mostPopular={true} />
      </SectionProductsContainer>

    </Layout>
  )
}
