import Head from 'next/head'
import Header from '../components/header'
import Layout from '../components/layout'
import Banner from '../components/banner'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Tiendita project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <Banner  /> 
    </Layout>
  )
}
