import Head from 'next/head'
import Header from '../components/header'
import Layout from '../components/layout'
import Banner from '../components/banner'
import SectionProducts from '../components/section-products'
import { useState, useEffect } from 'react'
import db from '../db/index'
import SectionProductsContainer from '../components/section-products-container'
import Modal from '../components/modal-portal'


export default function Home() {
  let [popular, setAllPopular] = useState(null)
  let [offertProducts, setOffertProducts] = useState(null)
  let [ modal, setModal ] = useState(false)
  let [ address, setAddress ] = useState('México City Marriott Reforma Hotel Puta')
  let [ oneSelectProduct, setOneProduct ] = useState()


  useEffect(() => {
    if(db){
      let productsOffert = db.filter( product  => product.price.offert)
      setOffertProducts(productsOffert)
      let mostPopularProduct = db.filter( product => product.popular)
      setAllPopular(mostPopularProduct)
    }
  }, [])



  return (
    <Layout>
      <Head>
        <title>Tiendita project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Modal 
        product={oneSelectProduct} 
        setAddress={setAddress} 
        modal={modal} 
        setModal={setModal}
        type='product'
        />


      <Header address={address} setModal={setModal} />
      <Banner  />
      <SectionProductsContainer>
        <SectionProducts setOneProduct={setOneProduct} setModal={setModal} title="Ofertas" products={offertProducts} />
        <SectionProducts setOneProduct={setOneProduct} setModal={setModal} title="Lo más popular" products={popular} mostPopular={true} />
      </SectionProductsContainer>

    </Layout>
  )
}
